-- ============================================================================
-- CloudSense AI -- BigQuery Schema Reference (GENERATED FILE, DO NOT HAND-EDIT)
-- ============================================================================
-- This file is a static, human-readable export of the DDL generated by
-- src/pipeline/bigquery_client.py::generate_full_schema_ddl(), which is
-- itself driven entirely by the schema definitions in
-- src/pipeline/schema.py (GOLD_TABLE_SCHEMAS, MART_TABLE_SCHEMAS,
-- BIGQUERY_SPECS). The Python module is the single source of truth --
-- regenerate this file (do not hand-edit it) by running:
--
--   python3 -c "from src.pipeline.bigquery_client import generate_full_schema_ddl; print(generate_full_schema_ddl('cloudsense_dw'))" > sql/bigquery/schema_reference.sql
--
-- Replace the dataset name ('cloudsense_dw') with your actual dataset if
-- different. The migration script (run_bigquery_migration.py) does NOT
-- read this file -- it calls generate_full_schema_ddl() directly.
-- ============================================================================

-- ============================================================================
-- CloudSense AI: Google BigQuery Schema DDL (generated from src/pipeline/schema.py)
-- Dataset: cloudsense_dw
-- ============================================================================


CREATE SCHEMA IF NOT EXISTS `cloudsense_dw`
OPTIONS(
  description="CloudSense AI Enterprise FinOps & GreenOps Data Warehouse",
  location="US"
);


-- ----------------------------------------------------------------------------
-- DIMENSION TABLES
-- ----------------------------------------------------------------------------


CREATE OR REPLACE TABLE `cloudsense_dw.dim_date` (
  date_key INT64,
  full_date STRING,
  year INT64,
  quarter INT64,
  month INT64,
  month_name STRING,
  week_of_year INT64,
  day_of_month INT64,
  day_of_week INT64,
  day_name STRING,
  is_weekend BOOL,
  is_month_end BOOL
)
OPTIONS(description="CloudSense AI — dim_date");

CREATE OR REPLACE TABLE `cloudsense_dw.dim_provider` (
  provider_id STRING,
  provider_name STRING,
  cloud_category STRING,
  headquarters STRING
)
OPTIONS(description="CloudSense AI — dim_provider");

CREATE OR REPLACE TABLE `cloudsense_dw.dim_region` (
  region_id STRING,
  region_name STRING,
  country STRING,
  continent STRING,
  pue_factor FLOAT64,
  grid_carbon_intensity_gco2_per_kwh FLOAT64,
  renewable_tier STRING
)
OPTIONS(description="CloudSense AI — dim_region");

CREATE OR REPLACE TABLE `cloudsense_dw.dim_service` (
  service_id STRING,
  service_name STRING,
  service_family STRING,
  pricing_unit STRING,
  pricing_model STRING
)
OPTIONS(description="CloudSense AI — dim_service");

CREATE OR REPLACE TABLE `cloudsense_dw.dim_resource` (
  resource_id STRING,
  resource_name STRING,
  resource_type STRING,
  project_id STRING,
  project_name STRING,
  department STRING,
  cost_center STRING,
  environment STRING,
  service_id STRING,
  region_id STRING,
  pricing_tier STRING,
  provisioned_vcpu FLOAT64,
  provisioned_memory_gb FLOAT64,
  provisioned_storage_gb FLOAT64
)
OPTIONS(description="CloudSense AI — dim_resource");


-- ----------------------------------------------------------------------------
-- FACT TABLES (Partitioned & Clustered)
-- ----------------------------------------------------------------------------


CREATE OR REPLACE TABLE `cloudsense_dw.fact_usage` (
  usage_fact_id STRING,
  date_key INT64,
  usage_date DATE,
  resource_id STRING,
  service_id STRING,
  region_id STRING,
  provider_id STRING,
  runtime_hours FLOAT64,
  usage_quantity FLOAT64,
  pricing_unit STRING,
  avg_cpu_utilization_pct FLOAT64,
  max_cpu_utilization_pct FLOAT64,
  avg_memory_utilization_pct FLOAT64,
  max_memory_utilization_pct FLOAT64,
  disk_read_iops FLOAT64,
  disk_write_iops FLOAT64,
  network_ingress_gb FLOAT64,
  network_egress_gb FLOAT64,
  total_requests INT64,
  is_idle BOOL
)
PARTITION BY usage_date
CLUSTER BY resource_id, service_id, region_id
OPTIONS(description="CloudSense AI — fact_usage");

CREATE OR REPLACE TABLE `cloudsense_dw.fact_cost` (
  cost_fact_id STRING,
  date_key INT64,
  usage_date DATE,
  resource_id STRING,
  service_id STRING,
  region_id STRING,
  provider_id STRING,
  pricing_tier STRING,
  usage_quantity FLOAT64,
  list_unit_price_usd FLOAT64,
  list_cost_usd FLOAT64,
  discount_amount_usd FLOAT64,
  net_cost_usd FLOAT64,
  effective_hourly_rate FLOAT64
)
PARTITION BY usage_date
CLUSTER BY resource_id, service_id, region_id
OPTIONS(description="CloudSense AI — fact_cost");

CREATE OR REPLACE TABLE `cloudsense_dw.fact_carbon` (
  carbon_fact_id STRING,
  date_key INT64,
  usage_date DATE,
  resource_id STRING,
  service_id STRING,
  region_id STRING,
  provider_id STRING,
  runtime_hours FLOAT64,
  server_power_avg_watts FLOAT64,
  energy_consumed_kwh FLOAT64,
  scope2_location_based_gco2e FLOAT64,
  scope3_embodied_gco2e FLOAT64,
  total_carbon_gco2e FLOAT64,
  emissions_per_dollar_usd FLOAT64
)
PARTITION BY usage_date
CLUSTER BY region_id, service_id
OPTIONS(description="CloudSense AI — fact_carbon");

CREATE OR REPLACE TABLE `cloudsense_dw.fact_anomaly` (
  anomaly_fact_id STRING,
  date_key INT64,
  usage_date DATE,
  resource_id STRING,
  service_id STRING,
  region_id STRING,
  provider_id STRING,
  anomaly_type STRING,
  actual_cost_usd FLOAT64,
  expected_cost_usd FLOAT64,
  deviation_usd FLOAT64,
  deviation_pct FLOAT64,
  severity STRING,
  root_cause_description STRING
)
PARTITION BY usage_date
CLUSTER BY severity, anomaly_type, service_id
OPTIONS(description="CloudSense AI — fact_anomaly");


-- ----------------------------------------------------------------------------
-- ANALYTICS MART TABLES (Pre-Aggregated Presentation Layer)
-- ----------------------------------------------------------------------------


CREATE OR REPLACE TABLE `cloudsense_dw.mart_cost_summary` (
  department STRING,
  project_name STRING,
  environment STRING,
  service_family STRING,
  service_name STRING,
  region_name STRING,
  total_list_cost_usd FLOAT64,
  total_discounts_usd FLOAT64,
  total_net_cost_usd FLOAT64,
  avg_daily_net_cost_usd FLOAT64,
  total_energy_kwh FLOAT64,
  total_carbon_kg FLOAT64,
  active_resource_count INT64,
  total_records INT64
)
CLUSTER BY department, service_family
OPTIONS(description="CloudSense AI — mart_cost_summary");

CREATE OR REPLACE TABLE `cloudsense_dw.mart_cost_trends` (
  usage_date DATE,
  total_net_cost_usd FLOAT64,
  total_list_cost_usd FLOAT64,
  total_discount_usd FLOAT64,
  total_energy_kwh FLOAT64,
  total_carbon_kg FLOAT64,
  rolling_7d_avg_cost FLOAT64,
  rolling_30d_avg_cost FLOAT64,
  daily_growth_pct FLOAT64
)
PARTITION BY usage_date
OPTIONS(description="CloudSense AI — mart_cost_trends");

CREATE OR REPLACE TABLE `cloudsense_dw.mart_resource_utilization` (
  resource_id STRING,
  resource_name STRING,
  service_name STRING,
  resource_type STRING,
  department STRING,
  environment STRING,
  provisioned_vcpu FLOAT64,
  provisioned_memory_gb FLOAT64,
  mean_cpu_pct FLOAT64,
  p95_cpu_pct FLOAT64,
  mean_ram_pct FLOAT64,
  p95_ram_pct FLOAT64,
  total_net_spend_usd FLOAT64,
  total_carbon_kg FLOAT64,
  idle_days_count INT64,
  utilization_tier STRING
)
CLUSTER BY department, environment
OPTIONS(description="CloudSense AI — mart_resource_utilization");

CREATE OR REPLACE TABLE `cloudsense_dw.mart_anomalies` (
  anomaly_type STRING,
  severity STRING,
  root_cause_description STRING,
  incident_days_count INT64,
  affected_resources_count INT64,
  total_actual_cost_usd FLOAT64,
  total_expected_cost_usd FLOAT64,
  total_deviation_usd FLOAT64,
  avg_deviation_pct FLOAT64,
  earliest_detected STRING,
  latest_detected STRING
)
CLUSTER BY severity, anomaly_type
OPTIONS(description="CloudSense AI — mart_anomalies");

CREATE OR REPLACE TABLE `cloudsense_dw.mart_optimization_opportunities` (
  optimization_category STRING,
  resource_id STRING,
  resource_name STRING,
  service_name STRING,
  department STRING,
  active_days INT64,
  current_monthly_spend FLOAT64,
  current_monthly_carbon_kg FLOAT64,
  estimated_monthly_savings_usd FLOAT64,
  estimated_annual_savings_usd FLOAT64,
  estimated_monthly_carbon_saved_kg FLOAT64
)
CLUSTER BY optimization_category, department
OPTIONS(description="CloudSense AI — mart_optimization_opportunities");

CREATE OR REPLACE TABLE `cloudsense_dw.mart_carbon_emissions` (
  region_id STRING,
  region_name STRING,
  grid_carbon_intensity_gco2_per_kwh FLOAT64,
  total_net_spend_usd FLOAT64,
  total_energy_kwh FLOAT64,
  scope2_operational_kg FLOAT64,
  scope3_embodied_kg FLOAT64,
  total_carbon_kg FLOAT64,
  carbon_per_dollar_gco2e FLOAT64
)
CLUSTER BY region_id
OPTIONS(description="CloudSense AI — mart_carbon_emissions");
